import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import axios from 'axios';
import {useState} from 'react';
import {BSSearch} from 'react-icons/bs';
import {getWeatherByCity} from '@/services/weather';
import Weather from '@/components/Weather';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  const handleFormSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);

    getWeatherByCity(city).then((data) => setWeather(data));
    setCity('');
    setLoading(false);
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <form>
          <input type="text" value={city} placeholder='Search city' onChange={(e) => setCity(e.target.value)}/>
          <button onClick={handleFormSubmit}>Fetch data</button>
        </form>
        {weather && weather.main && <Weather data={weather}/>}
      </main>
    </>
  )
}
